### ISSUE TITLE
Header Text

### ISSUE THREAD

**Issue by rashid-sial** [topcoderinc/TCO_Megahack_eRules_Search_Engine_Frontend#13]
Update the text in the header to:

**# EPA - eRules Search Engine**
Welcome to the eRules search engine - the eRSE provides a capability for you to search against pending EPA laws and regulations based on specified criteria. You can also expand the results and determine how they're related to the Clean Air Act as well as show linkages from the laws or regulations to programs that might be related.

![image](https://cloud.githubusercontent.com/assets/5807576/20247025/fbae002c-a988-11e6-8516-ad308441c328.png)

**Comment by alamora** [comment]
## Offering a tweak to the language:

Welcome to the eRules search engine - the eRSE provides a capability for you to search against the list of rules and regulations that the EPA is proposing in order to enforce legislation that has been recently passed by Congress.  Each of these rules is open for comment and the EPA wants your input!  Through this tool you can expand the results and determine how they're related to the Clean Air Act, as well as see linkages from the proposed rules to programs that might be related.

**Comment by alamora** [comment]
Rash - although users are not commenting through our app, each of the rules listed should link to regulations.gov, where people _can_ comment.  I dont think we mentioned that in our docs but its an obvious addition (because the API itself is coming from regulations.gov so all you have to do is link by docket #).

**Comment by rashid-sial** [comment]
Sounds good.

Johnny please use the updated text. And for the title "EPA - eRules Search Engine" please make that larger so it stands out.

**Comment by jarnanchen** [comment]
Fixed

**Comment by rashid-sial** [comment]
Fixed.
